name = "somity-web"
compatibility_date = "2026-06-27"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "somity-db"
database_id = "f77e3526-4757-40b1-8295-ed9cf0a1c807"
